import type { Category, DomainPanel, IndicatorMetric, Stock } from "./types";

const favicon = (domain: string) =>
    `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;

export const stocks: Stock[] = [
    {
        sym: "AAPL",
        name: "Apple Inc.",
        cat: "stocks",
        price: 271.06,
        d7: 2.14,
        m1: 7.72,
        y1: 30.65,
        ath: -6.1,
        cap: "$3.98T",
        spark: [248, 252, 255, 253, 265, 269, 271],
        logoUrl: favicon("apple.com"),
    },
    {
        sym: "MSFT",
        name: "Microsoft Corp.",
        cat: "stocks",
        price: 418.32,
        d7: 3.81,
        m1: 5.43,
        y1: 18.22,
        ath: -2.3,
        cap: "$3.11T",
        spark: [398, 405, 409, 414, 416, 420, 418],
        logoUrl: favicon("microsoft.com"),
    },
    {
        sym: "NVDA",
        name: "NVIDIA Corp.",
        cat: "stocks",
        price: 882.4,
        d7: 8.33,
        m1: 14.62,
        y1: 61.2,
        ath: -19.3,
        cap: "$2.16T",
        spark: [810, 826, 845, 862, 871, 879, 882],
        logoUrl: favicon("nvidia.com"),
    },
    {
        sym: "GOOGL",
        name: "Alphabet Inc.",
        cat: "stocks",
        price: 167.94,
        d7: -1.04,
        m1: 4.11,
        y1: 22.8,
        ath: -8.6,
        cap: "$2.05T",
        spark: [171, 170, 168, 165, 164, 169, 168],
        logoUrl: favicon("google.com"),
    },
    {
        sym: "AMZN",
        name: "Amazon.com Inc.",
        cat: "stocks",
        price: 195.21,
        d7: 5.66,
        m1: 9.3,
        y1: 34.1,
        ath: -5.4,
        cap: "$2.07T",
        spark: [183, 186, 188, 191, 194, 196, 195],
        logoUrl: favicon("amazon.com"),
    },
    {
        sym: "TSLA",
        name: "Tesla Inc.",
        cat: "stocks",
        price: 248.15,
        d7: -4.72,
        m1: -6.31,
        y1: 12.44,
        ath: -46.8,
        cap: "$794B",
        spark: [265, 261, 257, 251, 250, 245, 248],
        logoUrl: favicon("tesla.com"),
    },
    {
        sym: "JPM",
        name: "JPMorgan Chase",
        cat: "stocks",
        price: 231.44,
        d7: 1.18,
        m1: 4.65,
        y1: 29.8,
        ath: -2.8,
        cap: "$669B",
        spark: [227, 228, 229, 230, 231, 233, 231],
        logoUrl: favicon("jpmorganchase.com"),
    },
    {
        sym: "V",
        name: "Visa Inc.",
        cat: "stocks",
        price: 339.8,
        d7: 1.54,
        m1: 3.88,
        y1: 21.6,
        ath: -1.2,
        cap: "$691B",
        spark: [333, 334, 336, 338, 339, 341, 340],
        logoUrl: favicon("visa.com"),
    },
    {
        sym: "BRK.B",
        name: "Berkshire Hathaway",
        cat: "stocks",
        price: 468.2,
        d7: 0.73,
        m1: 2.44,
        y1: 17.9,
        ath: -0.8,
        cap: "$1.01T",
        spark: [464, 465, 466, 467, 468, 469, 468],
        logoUrl: favicon("berkshirehathaway.com"),
        logoFallback: "BRK",
    },
    {
        sym: "XOM",
        name: "Exxon Mobil Corp.",
        cat: "stocks",
        price: 112.37,
        d7: -2.41,
        m1: -3.1,
        y1: 8.6,
        ath: -9.4,
        cap: "$449B",
        spark: [117, 115, 114, 113, 112, 111, 112],
        logoUrl: favicon("exxonmobil.com"),
    },
    {
        sym: "NEE",
        name: "NextEra Energy",
        cat: "stocks",
        price: 74.22,
        d7: 0.94,
        m1: 3.12,
        y1: 14.5,
        ath: -18.4,
        cap: "$152B",
        spark: [72, 73, 73, 74, 74, 75, 74],
        logoUrl: favicon("nexteraenergy.com"),
    },
    {
        sym: "BTC",
        name: "Bitcoin",
        cat: "crypto",
        price: 96418,
        d7: 2.65,
        m1: 11.3,
        y1: 88.4,
        ath: -15.2,
        cap: "$1.90T",
        spark: [91000, 92800, 94100, 95200, 96000, 97100, 96418],
        logoUrl: favicon("bitcoin.org"),
    },
    {
        sym: "ETH",
        name: "Ethereum",
        cat: "crypto",
        price: 1822,
        d7: -3.14,
        m1: -8.4,
        y1: 24.6,
        ath: -62.3,
        cap: "$219B",
        spark: [1920, 1900, 1880, 1855, 1840, 1810, 1822],
        logoUrl: favicon("ethereum.org"),
    },
    {
        sym: "SOL",
        name: "Solana",
        cat: "crypto",
        price: 148.32,
        d7: 6.11,
        m1: 18.2,
        y1: 142,
        ath: -55.1,
        cap: "$69B",
        spark: [130, 136, 140, 143, 147, 151, 148],
        logoUrl: favicon("solana.com"),
    },
    {
        sym: "GOLD",
        name: "Gold Spot",
        cat: "commodities",
        price: 3304,
        d7: 0.73,
        m1: 5.4,
        y1: 28.2,
        ath: -0.4,
        cap: "-",
        spark: [3241, 3260, 3275, 3288, 3295, 3310, 3304],
        logoUrl: favicon("gold.org"),
        logoFallback: "AU",
    },
    {
        sym: "SILVER",
        name: "Silver Spot",
        cat: "commodities",
        price: 32.14,
        d7: -1.22,
        m1: 2.8,
        y1: 18.6,
        ath: -38.2,
        cap: "-",
        spark: [33.1, 32.8, 32.5, 32.2, 32, 31.9, 32.1],
        logoUrl: favicon("silverinstitute.org"),
        logoFallback: "AG",
    },
    {
        sym: "COPPER",
        name: "Copper Futures",
        cat: "commodities",
        price: 4.88,
        d7: 3.4,
        m1: 7.2,
        y1: 22.1,
        ath: -12.8,
        cap: "-",
        spark: [4.6, 4.68, 4.72, 4.78, 4.83, 4.9, 4.88],
        logoUrl: favicon("lme.com"),
        logoFallback: "CU",
    },
    {
        sym: "CORN",
        name: "Corn Futures",
        cat: "commodities",
        price: 472,
        d7: -1.8,
        m1: -4.2,
        y1: -8.4,
        ath: -38.6,
        cap: "-",
        spark: [488, 485, 482, 478, 474, 470, 472],
        logoUrl: favicon("cmegroup.com"),
    },
    {
        sym: "OIL",
        name: "WTI Crude Oil",
        cat: "commodities",
        price: 61.44,
        d7: -3.2,
        m1: -8.6,
        y1: -22.4,
        ath: -54.2,
        cap: "-",
        spark: [67, 65, 64, 63, 62, 61, 61],
        logoUrl: favicon("cmegroup.com"),
    },
    {
        sym: "WHEAT",
        name: "Wheat Futures",
        cat: "commodities",
        price: 541,
        d7: 2.1,
        m1: 4.3,
        y1: -5.2,
        ath: -52.8,
        cap: "-",
        spark: [524, 527, 530, 534, 538, 543, 541],
        logoUrl: favicon("cmegroup.com"),
    },
];

export const filters: { label: string; value: Category }[] = [
    { label: "All", value: "all" },
    { label: "Stocks", value: "stocks" },
    { label: "Crypto", value: "crypto" },
    { label: "Commodities", value: "commodities" },
];

export const domainPanels: DomainPanel[] = [
    {
        title: "Stocks",
        badge: "US Equities",
        accent: "blue",
        metrics: [
            {
                label: "S&P 500",
                value: "5,712",
                sub: "+0.84%",
                tone: "emerald",
            },
            {
                label: "VIX",
                value: "22.14",
                sub: "-3.40% elevated",
                tone: "amber",
            },
            {
                kind: "rsi",
                label: "Avg RSI",
                value: "54.8",
                rsi: 54.8,
                tone: "neutral",
            },
            {
                kind: "gauge",
                label: "Fear & Greed",
                value: "48",
                sub: "Neutral",
                score: 48,
                tone: "amber",
            },
        ],
    },
    {
        title: "Crypto",
        badge: "Digital Assets",
        accent: "amber",
        metrics: [
            {
                label: "Total Mkt Cap",
                value: "$3.12T",
                sub: "+1.42% today",
                tone: "emerald",
            },
            {
                label: "BTC Dom.",
                value: "61.4%",
                sub: "+0.3%",
                tone: "emerald",
            },
            {
                kind: "rsi",
                label: "Avg RSI",
                value: "58.2",
                rsi: 58.2,
                tone: "neutral",
            },
            {
                kind: "gauge",
                label: "Fear & Greed",
                value: "65",
                sub: "Greed",
                score: 65,
                tone: "emerald",
            },
        ],
    },
    {
        title: "Commodities",
        badge: "Futures & Spot",
        accent: "emerald",
        metrics: [
            {
                label: "Gold Spot",
                value: "$3,304",
                sub: "+0.73%",
                tone: "emerald",
            },
            {
                label: "WTI Crude",
                value: "$61.44",
                sub: "-3.20%",
                tone: "rose",
            },
            {
                kind: "rsi",
                label: "Avg RSI",
                value: "46.3",
                rsi: 46.3,
                tone: "neutral",
            },
            {
                kind: "gauge",
                label: "Fear & Greed",
                value: "32",
                sub: "Fear",
                score: 32,
                tone: "rose",
            },
        ],
    },
];

export const indicators: IndicatorMetric[] = [
    {
        label: "Total Mkt Cap",
        value: "$47.2T",
        sub: "+0.84% today",
        tone: "emerald",
    },
    { label: "S&P 500", value: "5,712", sub: "+0.84%", tone: "emerald" },
    {
        label: "VIX Volatility",
        value: "22.14",
        sub: "-3.40% elevated",
        tone: "amber",
    },
    {
        label: "Gold Spot",
        value: "$3,304",
        sub: "+0.73%",
        tone: "emerald",
    },
    {
        label: "WTI Crude Oil",
        value: "$61.44",
        sub: "-3.20%",
        tone: "rose",
    },
];
